### ISSUE TITLE
NameError: global name 'extractlink' is not defined

### ISSUE THREAD

**Issue by eluvatl** [Masood-M/yalih#1]
Hello. Is the IMAP protocol the only email protocol that can be used with this pot?

**Comment by eluvatl** [comment]
I am receiving an error when I use mail.clf.ex.

**Comment by Masood-M** [comment]
unfortunately, yes, at the moment it is the only protocol supported.

**Comment by eluvatl** [comment]
Thank you for your reply. I almost have everything working, however when I run the command:
Honeypot.py --email
I get an error at the end: 

NameError: global name 'extractlink' is not defined (see attached screenshot)
Is this something that I need to configure in honeypot.py? 

Please advise. 

Lexi


On Apr 21, 2016, at 4:37 AM, Masood Mansoori <notifications@github.com> wrote:


unfortunately, yes, at the moment it is the only protocol supported.—

**Comment by eluvatl** [comment]
Hello?

**Comment by Masood-M** [comment]
you need to import the extractlink.py in the honeypot.py file, simply add the following line at the beginning of the honeypot.py file:

import extractlink

also remove the # from the honeypot.py in the #email section
#		scan.scanning(path)
#		yaradetection.listandscan(path)

I hope this helps
